# Generated by Django 5.1.2 on 2024-10-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('error_type', models.CharField(max_length=100)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('last_occurred', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
