# Generated by Django 5.1.2 on 2024-10-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='last_occurred',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='occurrence_count',
        ),
    ]
