# Generated by Django 5.1.2 on 2024-10-30 21:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_tracker', '0002_remove_errorlog_last_occurred_and_more'),
        ('project_integrations', '0002_remove_apikey_project_name_project_apikey_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='error_type',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlog',
            name='environment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_integrations.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlog',
            name='error_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='error_tracker.errorgroup'),
        ),
    ]
